name: ninja
description: Encryption and Decryption cryptographic algorithms exposed as Dart's Converter and Codec interfaces.
version: 1.0.0
homepage: https://github.com/Jaguar-dart/ninja
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.60.0 <2.0.0'

dependencies:
  pointycastle: ^1.0.0-rc2

dev_dependencies:
  test: ^1.2.0
